import Vue from "vue";
import {
  Grid,
  GridItem,
  PullRefresh,
  Icon,
  Tab,
  Tabs,
  List,
  Cell,
  Button,
  SwipeCell,
  Popup,
  Field,
  Dialog,
  Toast,
  Swipe,
  Form,
  Search,
  SwipeItem,
  AddressList,
  Divider,
  Area,
  RadioGroup,
  Uploader,
  Radio,
  NavBar,
  CellGroup,
  DatetimePicker,
  ContactCard,
  ContactList,
  ContactEdit,
  Picker,
  Image,
  Sticky,
  Switch,
  Overlay,
  Calendar,
  Col,
  Row,
  Card,
  Checkbox,
  CheckboxGroup
} from "vant";

Vue.use(Icon);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(List);
Vue.use(Cell);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Field);
Vue.use(Dialog);
Vue.use(Toast);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(AddressList);
Vue.use(Area);
Vue.use(NavBar);
Vue.use(CellGroup);
Vue.use(Image);
Vue.use(Switch);
Vue.use(Sticky);
Vue.use(Divider);
Vue.use(Overlay);
Vue.use(Calendar);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(DatetimePicker);
Vue.use(Col);
Vue.use(Row);
Vue.use(Form);
Vue.use(Picker);
Vue.use(Uploader);
Vue.use(ContactCard);
Vue.use(ContactList);
Vue.use(ContactEdit);
Vue.use(PullRefresh);
Vue.use(SwipeCell);
Vue.use(Card);
Vue.use(Search);
Vue.use(Grid);
Vue.use(GridItem);
